apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: readiness-controller-webhook
  labels:
    {{- include "readiness-controller.labels" . | nindent 4 }}
webhooks:
  - name: readiness-controller.readiness-controller.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
    
    failurePolicy: Ignore

    clientConfig:
      service:
        name: {{ include "readiness-controller.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
        port: 8443
      
      caBundle: "Cg==" 

    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]

    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: 
            - kube-system
            # - {{ .Release.Namespace }}