apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: probes.probes.ready.io
spec:
  group: probes.ready.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Healthy
          type: boolean
          jsonPath: .status.healthy
        - name: Message
          type: string
          jsonPath: .status.message
        - name: Last Probe
          type: date
          jsonPath: .status.lastProbeTime
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                checkType:
                  type: string
                  enum: ["http", "tcp", "exec"]
                checkTarget:
                  type: string
                interval:
                  type: string
                timeout:
                  type: string
            status:
              type: object
              properties:
                healthy:
                  type: boolean
                lastProbeTime:
                  type: string
                  format: date-time
                message:
                  type: string
  scope: Namespaced
  names:
    plural: probes
    singular: probe
    kind: Probe
    shortNames:
      - pr
